CREATE TABLE P_USER (
  ID       INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  USERNAME VARCHAR(16)                        NOT NULL,
  PASSWORD VARCHAR(16)                        NOT NULL
)DEFAULT CHARSET = utf8,ENGINE = InnoDB;
CREATE TABLE P_GAME (
  ID       INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  GAMENAME VARCHAR(16)                        NOT NULL,
  GAMEDESCRIPTION TEXT,
  FILEPATH VARCHAR(256),
  GAMEAPK LONGBLOB
)DEFAULT CHARSET = utf8,ENGINE = InnoDB;
